<?php
// model/Member.php - handles all DB work for members
// Connect to MySQL (hardcoded as the spec asks)
function db_connect() {
    $conn = mysqli_connect("localhost", "root", "", "library_db");
    if (!$conn) {
        die("DB connection failed: " . mysqli_connect_error()); //die() stops execution and shows the error message
    }
    return $conn;
}
// Check if a username already exists -> blocks duplicates
function memberExists($username) {
    $conn = db_connect();
    $username = mysqli_real_escape_string($conn, $username);
    $sql = "SELECT id FROM members WHERE username='$username'";
    $result = mysqli_query($conn, $sql);
    $exists = (mysqli_num_rows($result) > 0);
    mysqli_close($conn);
    return $exists;
}
// Insert a new member into the table after moving the uploaded photo
function addMember($name, $email, $username, $password, $photoTmp, $photoName) {
    // Move photo to uploads folder
    $newName = time() . "_" . basename($photoName);
    move_uploaded_file($photoTmp, __DIR__ . "/../views/static/uploads/" . $newName); // to remember this line for the 
    // exam, it moves the uploaded file from its temporary location to the specified directory with a new name that 
    // includes a timestamp to avoid conflicts // the $newName is generated by concatenating the current timestamp 
    // (time()) with the original filename (basename($photoName)) to ensure uniqueness and prevent overwriting existing 
    // files in the uploads directory.
 
    //$photoTmp is the temporary file path of the uploaded photo, and $photoName is the original name of the uploaded 
    // file.

    // Save to database
    $conn = db_connect();
    $sql  = "INSERT INTO members (name, email, username, password, photo)
             VALUES ('$name', '$email', '$username', '$password', '$newName')";
    mysqli_query($conn, $sql);
    mysqli_close($conn);
}
?>
